# -*- coding: utf-8 -*-
# mysql configuration
MYSQL_HOST = '*'
MYSQL_USER = '*'
MYSQL_PASSWORD = '*'
MYSQL_PORT = 3306
MYSQL_DATABASE = 'ica'

# ON-OFF
ENABLE_GETTER = False
ENABLE_POJIE = False
ENABLE_ZHUANKEBABA = True
ENABLE_WEIBO = False

# getter采集周期
GETTER_CYCLE = 60

# zhuankebaba采集周期
ZHUANKEBABA_CYCLE = 2000

# weibo configuration
WEIBO_CYCLE = 2000
WEIBO_BEGIN_OFFSET = 1
WEIBO_END_OFFSET = 50
WEIBO_COOKIE_POOL_URL = 'http://47.96.88.67:5000/weibo/random'

# 52pojie configuration
KEYWORDS = ['苏宁', '易购', 'suning', 'sn', '茅台', '飞天']
POJIE_BASE_URL = 'https://www.52pojie.cn/'
POJIE_GROUP_START = 0
POJIE_GROUP_END = 6
POJIE_CYCLE = 2000

# tables
MYSQL_TABLE_TUAN_XIANBAO = 'tuan_xianbao'
MYSQL_TABLE_JUST_XIANBAO = 'just_xianbao'
MYSQL_TABLE_ZY_BAICAI = 'zy_baicai'
MYSQL_TABLE_ZY_TENYUANSTORE = 'zy_tenyuanstore'
MYSQL_TABLE_TAO_CLIPCOUPONS = 'tao_clipcoupons'
MYSQL_TABLE_TAO_RTINFO = 'tao_rtinfo'
MYSQL_TABLE_TAO_ACTIVITYINFO = 'tao_activityinfo'
MYSQL_TABLE_POJIE = 'pojie'
MYSQL_TABLE_ZHUANKEBABA = 'zhuankebaba'
MYSQL_TABLE_WEIBO = 'weibo'

# tuan0818 information
SQL_CREATE_TUANXIANBAO_TABLE = """
CREATE TABLE IF NOT EXISTS {}(
id VARCHAR(25) NOT NULL,
keyword VARCHAR(50) NOT NULL,
source VARCHAR(50) NOT NULL,
title VARCHAR(510) NOT NULL,
post_on VARCHAR(255) NOT NULL,
url VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
)ENGINE=INNODB CHARSET=UTF8""".format(MYSQL_TABLE_TUAN_XIANBAO)

# just999
SQL_CREATE_JUST_TABLE = """
CREATE TABLE IF NOT EXISTS {}(
id VARCHAR(25) NOT NULL,
keyword VARCHAR(50) NOT NULL,
source VARCHAR(50) NOT NULL,
title VARCHAR(510) NOT NULL,
post_on VARCHAR(255) NOT NULL,
url VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
)ENGINE=INNODB CHARSET=UTF8""".format(MYSQL_TABLE_JUST_XIANBAO)

# zhuanyes
SQL_CREATE_ZY_BAICAI_TABLE = """
CREATE TABLE IF NOT EXISTS {}(
id VARCHAR(25) NOT NULL,
keyword VARCHAR(50) NOT NULL,
source VARCHAR(50) NOT NULL,
title VARCHAR(510) NOT NULL,
post_on VARCHAR(255) NOT NULL,
url VARCHAR(255) NOT NULL,
content TEXT,
PRIMARY KEY(id)
)ENGINE=INNODB CHARSET=UTF8""".format(MYSQL_TABLE_ZY_BAICAI)

SQL_CREATE_ZY_TENYUANSTORE_TABLE = """
CREATE TABLE IF NOT EXISTS {}(
id VARCHAR(25) NOT NULL,
title VARCHAR(510) NOT NULL,
price VARCHAR(255) NOT NULL,
img VARCHAR(255) NOT NULL,
url VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
)ENGINE=INNODB CHARSET=UTF8
""".format(MYSQL_TABLE_ZY_TENYUANSTORE)

# 52pojie
SQL_CREATE_POJIE_TABLE = """
CREATE TABLE IF NOT EXISTS {}(
id VARCHAR(255) NOT NULL,
keyword VARCHAR(255) NOT NULL,
source VARCHAR(50) NOT NULL,
title VARCHAR(510) NOT NULL,
user_name VARCHAR(255) NOT NULL,
user_homepage VARCHAR(255) NOT NULL,
post_on VARCHAR(255) NOT NULL,
content TEXT,
url VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
)ENGINE=INNODB CHARSET=UTF8""".format(MYSQL_TABLE_POJIE)

# zhuankebaba
SQL_CREATE_ZHUANKEBABA_TABLE = """
CREATE TABLE IF NOT EXISTS {}(
id VARCHAR(255) NOT NULL,
keyword VARCHAR(255) NOT NULL,
source VARCHAR(50) NOT NULL,
title VARCHAR(510) NOT NULL,
post_on VARCHAR(255) NOT NULL,
category VARCHAR(255) NOT NULL,
contact VARCHAR(255) NOT NULL,
tag VARCHAR(255) NOT NULL,
content TEXT,
url VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
)ENGINE=INNODB CHARSET=UTF8""".format(MYSQL_TABLE_ZHUANKEBABA)

# weibo
SQL_CREATE_WEIBO_TABLE = """
CREATE TABLE IF NOT EXISTS {}(
id VARCHAR(255) NOT NULL,
keyword VARCHAR(255) NOT NULL,
source VARCHAR(50) NOT NULL,
comment TEXT,
title TEXT,
url VARCHAR(255) NOT NULL,
crawl_date VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
)ENGINE=INNODB CHARSET=UTF8""".format(MYSQL_TABLE_WEIBO)

# 79淘薅羊毛
SQL_CREATE_TAO_CLIPCOUPONS_TABLE = """
CREATE TABLE IF NOT EXISTS {}(
id VARCHAR(25) NOT NULL,
title VARCHAR(510) NOT NULL,
url VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
)ENGINE=INNODB CHARSET=UTF8
""".format(MYSQL_TABLE_TAO_CLIPCOUPONS)

# 79tao实时线报
SQL_CREATE_TAO_RTINFO_TABLE = """
CREATE TABLE IF NOT EXISTS {}(
id VARCHAR(25) NOT NULL,
title VARCHAR(510) NOT NULL,
url VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
)ENGINE=INNODB CHARSET=UTF8
""".format(MYSQL_TABLE_TAO_RTINFO)

# 79tao活动线报
SQL_CREATE_TAO_ACTIVITYINFO_TABLE = """
CREATE TABLE IF NOT EXISTS {}(
id VARCHAR(25) NOT NULL,
title VARCHAR(510) NOT NULL,
url VARCHAR(255) NOT NULL,
dt VARCHAR(50) NOT NULL,
PRIMARY KEY(id)
)ENGINE=INNODB CHARSET=UTF8
""".format(MYSQL_TABLE_TAO_ACTIVITYINFO)
